openapi: 3.0.0

info:
  # next-startup-cdkで作成した、localのApiGateway名を指定してください。
  title: NextStartUpApi-prod
  description: Production-API
  contact:
    name: 'API Support'
    url: https://github.com/yokohama/next-startup-mock
  lisense:
    name: Apache 2.0,
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

servers:
  - url: http://localhost:3000

security:
  - bearerAuth: [] 

paths:
  $ref: ./pet.yaml
