openapi: 3.0.0

info:
  # title: API Gateway用にデプロイ時に自動で書き換える。設定したい場合は、openapi/env.confで設定
  # description: API Gateway用にデプロイ時に自動で書き換える。設定したい場合は、openapi/env.confで設定
  title: NEXT-STARTUP-TITLE
  description: NEXT-STARTUP-DESC
  contact:
    name: 'API Support'
    url: https://github.com/yokohama/next-startup-mock
  version: 1.0.1

# ISSUE: 16
servers:
  - url: http://localhost:3000

security:
  - Bearer: []

paths:
  /users:
    get:
      tags:
        - users
      summary: Get all users.
      description: Returns an array of User model.
      parameters: []
      responses:
        '200':
          description: A Json array of User model.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                example:
                  - id: 1
                    name: Hoge Moge
                  - id: 2
                    name: Foo Bar
        '405':
          $ref: '#/components/responses/UnauthorizedError'
      x-amazon-apigateway-integration:
        type: "http_proxy" 
        httpMethod: "GET" 
        connectionType: "VPC_LINK" 
        connectionId: "{NEXT-STARTUP-VPC-LINK-ID}" 
        uri: "http://{NEXT-STARTUP-LB-URI}/users"

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
