name: '[ Production ] APIGateway deploy'

on:
  push:
    branches:
      - main
    paths:
      - 'openapi/**'
      - '.github/workflows/**'
        
jobs:
  Deploy-APIGateway:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          env: prod
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
